version: '3.3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: spring-mvc-war
    expose: 
      - 8080

  loadbalancer:
    image: 'dockercloud/haproxy:latest'
    container_name: loadbalancer   
    links:
      - web
    ports:
      - '8001:8080'      